### ISSUE TITLE
Any success with setup lando with vite, default frontend framework for laravel ?

### ISSUE THREAD

**Issue by abrampl** [lando/laravel#24]

**Comment by sinnbeck** [comment]
I got it working, but only with http, not https. I added a seperate service for node
```
  node:
    type: node:16
    ssl: true
    scanner: false
    ports:
      - 3009:3009
    build:
      - npm install
```
and 
```
tooling:
  dev:
    service: node
    cmd: npm run dev
```
and my server in `vite.config.js`
```
    server: {
        https: false,
        port: 3009,
        hmr: {host: '0.0.0.0'},
    },
```
If you have any luck getting it working with https, I would be interested in knowing this.
